### ISSUE TITLE
Issue with instantiation

### ISSUE THREAD

**Issue by teddy-mczieuwa** [AhmedAyachi/LinkerLine#4] opened 2024-03-22 14:02 UTC
Hi, thanks for your update on this library. I have the following issue when instantiating a new line:

Here is what my code looks like:

```
    let parentElement = document.querySelector('.zoomable-container')
    const line = new LinkerLine({ parent: parentElement , start: container, end: data.parentContainer})
```

And here is the error that I get:

`    The expected type comes from property 'parent' which is declared here on type 'LinkerLineProps'
`

and there is a red squiggly on the 'parent' property by typescript.

Please help, I do not understand what is happening

**Comment by AhmedAyachi** [comment] 2024-03-22 14:38
hello, is the error just a lint error or the line is not even getting instantiated, like not even present in the DOM ?

**Comment by teddy-mczieuwa** [comment] 2024-03-22 14:41
Hi @AhmedAyachi Thanks for your speedy response. 
The line does not get instantiated. Compilation fails and displays the error:
`   The expected type comes from property 'parent' which is declared here on type 'LinkerLineProps'
`

**Comment by AhmedAyachi** [comment] 2024-03-22 14:50
as it seems, you're using typescript, can you just try doing the same thing using only javascript (no typescript).
It should generate a similar error though but just asking to make sure I'm getting something to work with.
And can you please provide more info as the code snippet you sent is not that informative, like what are you trying to accomplish and what are the end, start elements, are they siblings, are in the same subtree, things like that.

**Comment by teddy-mczieuwa** [comment] 2024-03-22 15:03
Sure, just for context. I am using the library in an angular project, so typescript is required. Here is the way It is implemented in my project.


```
import { Injectable } from '@angular/core';
import { Board, BoardImage } from '@app/@features/boards/models/board.model';
import LinkerLine from "linkerline";

@Injectable({
  providedIn: 'root',
})
export class LinesService {
  lines: any = [];
  createLeaderLines(board: Board): void {
    let parentElement = document.querySelector('.zoomable-container')
    const containers = Array.from(document.querySelectorAll('.img-canvas')) as HTMLElement[];
    containers.forEach((container) => {
      const data = this.findParent(container, containers, board);
      if (data) {

        // const line = new LeaderLine(container, data.parentContainer, {
        //   startPlug: 'behind',
        //   endPlug: 'behind',
        //   path: 'grid',
        //   color: 'white',
        //   endSocket: 'auto',
        //   startSocket: 'auto',
        //   startSocketGravity: 5,
        //   endSocketGravity: 5,
        // });

        const line = new LinkerLine({ parent: parentElement , start: container, end: data.parentContainer}
        this.lines.push(line);
      }

    });
  }
  
  findParent(container: HTMLElement, containers: HTMLElement[], board: Board) {
    let img1: BoardImage | undefined;
    let img2: BoardImage | undefined;

    const xPos = parseInt(container.style.left || '0', 10);
    const yPos = parseInt(container.style.top || '0', 10);

    board.boardImages.forEach((img) => {
      if (img.xPos === xPos && img.yPos === yPos) {
        img1 = img;
      }
    });

    if (img1) {
      for (const parentContainer of containers) {
        const parentXPos = parseInt(parentContainer.style.left || '0', 10);
        const parentYPos = parseInt(parentContainer.style.top || '0', 10);

        board.boardImages.forEach((img) => {
          if (img.xPos === parentXPos && img.yPos === parentYPos) {
            img2 = img;
          }
        });

        if (img2) {
          if (img1.parent && img1.parent.key === img2.key) {
            return { parentContainer, container };
          }
        }
      }
    }

    return null;
  }

}

```


The commented lines was how I used to implement the line connection in leaderline.js

**Comment by teddy-mczieuwa** [comment] 2024-03-22 15:19
Here's a link to my attempt with just javascript:
[https://stackblitz.com/edit/vitejs-vite-rt2wqw?file=index.html,main.js,style.css&terminal=dev](https://stackblitz.com/edit/vitejs-vite-rt2wqw?file=index.html,main.js,style.css&terminal=dev)

On the console, it logs:

>  Uncaught Error: `start` and `end` are required.

**Comment by AhmedAyachi** [comment] 2024-03-22 15:38
because in the querySelector query string you need to add a "." to select the elements with "start" and "end" as classNames. I did that and it's working.
```
const startElement = document.querySelector('.start');
const endElement = document.querySelector('.end');
```
Is the LeaderLine commented part working on your angular project ?

**Comment by teddy-mczieuwa** [comment] 2024-03-22 15:43
Ah yes! of course, that works. And the LeaderLine commented part works for me but I can't use it because it is very limited for my use case.

**Comment by teddy-mczieuwa** [comment] 2024-03-22 15:46
But I still don't know why linkerline does not compile in my project
![Image 22 03 24 at 16 49](https://github.com/AhmedAyachi/LinkerLine/assets/41925684/4877ceae-673e-4805-92c6-92d3937eadce)

**Comment by AhmedAyachi** [comment] 2024-03-22 15:53
thanks for sending this, I'll take a look at it and get back to you.
Just to make things easier, if you have the time, can you create a quicky angular project in stackblitz in which you regenerate the error, that would be helpful.

**Comment by AhmedAyachi** [comment] 2024-03-22 16:17
@teddy-mczieuwa, I created a new project and that issue showed up, can you just edit your code to this:
```
const line = new LinkerLine({
    parent: parentElement as HTMLElement, 
    start: container as HTMLElement, 
    end: data.parentContainer as HTMLElement,
});
```
and see if it's solved ?

**Comment by teddy-mczieuwa** [comment] 2024-03-22 16:22
Hi @AhmedAyachi I tried it but it does not seem to solve the problem for me

![Image 22 03 24 at 17 21](https://github.com/AhmedAyachi/LinkerLine/assets/41925684/4c666878-2f7a-4ff0-8b0e-db8fafa44bfd)

**Comment by AhmedAyachi** [comment] 2024-03-22 16:26
yep problem with my lint, I pushed a new version to dev, try to install that one directly from the repo and get back to me:
```
npm i https://github.com/AhmedAyachi/LinkerLine/tree/dev
``` 
dont' forget to add "as HTMLElement" when testing the dev branch version.

**Comment by teddy-mczieuwa** [comment] 2024-03-22 16:33
It works but I have lots of lint errors

![Image 22 03 24 at 17 32](https://github.com/AhmedAyachi/LinkerLine/assets/41925684/fb5a27b5-d069-4367-9950-5d72f4ba63bf)

**Comment by AhmedAyachi** [comment] 2024-03-22 16:35
So, at least now I know what's going on, don't worry, just ignore it, all will be fixed in v **1.2.1**.

**Comment by teddy-mczieuwa** [comment] 2024-03-22 16:38
Okay thanks! I hope that happens very soon.😅

**Comment by AhmedAyachi** [comment] 2024-03-23 11:20
@teddy-mczieuwa, can you please share with me the lint errors messages, cause it seems they're related to your project as in mine everything is fine.

**Comment by teddy-mczieuwa** [comment] 2024-03-23 19:42
@AhmedAyachi Sure! here it is:
<img width="1339" alt="Screenshot 2024-03-23 at 20 40 41" src="https://github.com/AhmedAyachi/LinkerLine/assets/41925684/e4c3bbd9-5399-4331-b040-26b4d7c86afa">

**Comment by teddy-mczieuwa** [comment] 2024-03-23 20:35
Also, please would it be okay with you if I directly contact you regarding other aspects of the library. I need your advice on what your approach would be regarding adding certain features to this library

**Comment by AhmedAyachi** [comment] 2024-03-24 16:17
@teddy-mczieuwa, I have no problem with you directly contacting me, but I would rather you submit issues here if you need a fix or a new feature just for everybody to see it and take a look at it.
And by the way, I updated the dev branch, marked all optional props and options and exported all interfacesa and types in case you need to add something like "as LinkerLineProps", so please reinstall that again and tell me if the issue is fixed, thanks.

**Comment by teddy-mczieuwa** [comment] 2024-03-25 10:19
Yes, this works without any errors.

**Comment by teddy-mczieuwa** [comment] 2024-03-25 14:50
I've reached out to you on linkedIn. Please let's communicate.

**Closed as completed** 2024-03-25 16:28 UTC
